### ISSUE TITLE
Working with IE7/IE8

### ISSUE THREAD

**Issue by madebyiando** [spadin/coverphoto#1]
Have you found any workarounds for this working in IE 7 or 8? I was wondering if I could integrate the following http://code.google.com/p/explorercanvas/

Shaun

**Comment by spadin** [comment]
Explorercanvas adds canvas functionality to IE, but my plugin also uses something called the FileReader API for getting the image data of the uploaded image. That's how you're able to see the "uploaded" image while you drag it around. I created a branch called "ie-compatibiltity" showing the changes for adding excanvas, but I won't have a chance to look at the FileReader API polyfill today. 

This polyfill looks promising though:
https://github.com/Jahdrien/FileReader

Here are the changes I made for adding excanvas too:
https://github.com/spadin/coverphoto/commit/58ff5044957849d558a814c3baf5b2725b18b4d1

**Comment by madebyiando** [comment]
Hi Sandro

Thanks for getting back to me, I started implementing the Explorercanvas functionality then seen the FileReader accesss and realised it was a no goer. I cannot go down the Flash route either as it’s school based and a lot of schools have the flash plugin disabled as default.

Thanks again

Shaun

**Comment by macray125** [comment]
Please can you give me the code for saving the cropped and original size of the image in PHP and MySQL

Thanks.
